/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: chapter1.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @chapter1: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@chapter1()
	{
		this.StartPassage = "Chapter 1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
		passage26_Init();
		passage27_Init();
		passage28_Init();
		passage29_Init();
		passage30_Init();
		passage31_Init();
		passage32_Init();
		passage33_Init();
		passage34_Init();
		passage35_Init();
		passage36_Init();
		passage37_Init();
		passage38_Init();
		passage39_Init();
		passage40_Init();
		passage41_Init();
		passage42_Init();
		passage43_Init();
		passage44_Init();
		passage45_Init();
		passage46_Init();
		passage47_Init();
		passage48_Init();
		passage49_Init();
		passage50_Init();
		passage51_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Chapter 1

	void passage1_Init()
	{
		this.Passages[@"Chapter 1"] = new StoryPassage(@"Chapter 1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Now Rann the Kite brings home the night");
		yield return lineBreak();
		yield return text("      That Mang the Bat sets free--");
		yield return lineBreak();
		yield return text("   The herds are shut in byre and hut");
		yield return lineBreak();
		yield return text("      For loosed till dawn are we.");
		yield return lineBreak();
		yield return text("   This is the hour of pride and power,");
		yield return lineBreak();
		yield return text("      Talon and tush and claw.");
		yield return lineBreak();
		yield return text("   Oh, hear the call!--Good hunting all");
		yield return lineBreak();
		yield return text("      That keep the Jungle Law!");
		yield return lineBreak();
		yield return text("   Night-Song in the Jungle");
		yield return lineBreak();
		yield return text("   ");
		yield return lineBreak();
		yield return text("   ");
		yield return link("Page2", "Page2", null);
		yield break;
	}


	// .............
	// #2: Page2

	void passage2_Init()
	{
		this.Passages[@"Page2"] = new StoryPassage(@"Page2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("It was seven o'clock of a very warm evening in the Seeonee hills");
		yield return lineBreak();
		yield return text("when Father Wolf woke up from his day's rest, scratched himself,");
		yield return lineBreak();
		yield return text("yawned, and spread out his paws one after the other to get rid of");
		yield return lineBreak();
		yield return text("the sleepy feeling in their tips.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page3", "Page3", null);
		yield break;
	}


	// .............
	// #3: Page3

	void passage3_Init()
	{
		this.Passages[@"Page3"] = new StoryPassage(@"Page3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Mother Wolf lay with her big");
		yield return lineBreak();
		yield return text("gray nose dropped across her four tumbling, squealing cubs, and");
		yield return lineBreak();
		yield return text("the moon shone into the mouth of the cave where they all lived.");
		yield return lineBreak();
		yield return text("\"Augrh!\" said Father Wolf.  \"It is time to hunt again.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page4", "Page4", null);
		yield break;
	}


	// .............
	// #4: Page4

	void passage4_Init()
	{
		this.Passages[@"Page4"] = new StoryPassage(@"Page4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("He was going to spring down hill when a little shadow with a bushy tail");
		yield return lineBreak();
		yield return text("crossed the threshold and whined: \"Good luck go with you, O Chief");
		yield return lineBreak();
		yield return text("of the Wolves.  And good luck and strong white teeth go with noble");
		yield return lineBreak();
		yield return text("children that they may never forget the hungry in this world.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page5", "Page5", null);
		yield break;
	}


	// .............
	// #5: Page5

	void passage5_Init()
	{
		this.Passages[@"Page5"] = new StoryPassage(@"Page5", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("It was the jackal--Tabaqui, the Dish-licker--and the");
		yield return lineBreak();
		yield return text("wolves of India despise Tabaqui because he runs about making");
		yield return lineBreak();
		yield return text("mischief, and telling tales, and eating rags and pieces of leather");
		yield return lineBreak();
		yield return text("from the village rubbish-heaps.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page6", "Page6", null);
		yield break;
	}


	// .............
	// #6: Page6

	void passage6_Init()
	{
		this.Passages[@"Page6"] = new StoryPassage(@"Page6", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("But they are afraid of him too,");
		yield return lineBreak();
		yield return text("because Tabaqui, more than anyone else in the jungle, is apt to go");
		yield return lineBreak();
		yield return text("mad, and then he forgets that he was ever afraid of anyone, and");
		yield return lineBreak();
		yield return text("runs through the forest biting everything in his way.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page7", "Page7", null);
		yield break;
	}


	// .............
	// #7: Page7

	void passage7_Init()
	{
		this.Passages[@"Page7"] = new StoryPassage(@"Page7", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Even the tiger runs and hides when little Tabaqui goes mad, for madness is");
		yield return lineBreak();
		yield return text("the most disgraceful thing that can overtake a wild creature.  We");
		yield return lineBreak();
		yield return text("call it hydrophobia, but they call it dewanee--the madness--");
		yield return lineBreak();
		yield return text("and run.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page8", "Page8", null);
		yield break;
	}


	// .............
	// #8: Page8

	void passage8_Init()
	{
		this.Passages[@"Page8"] = new StoryPassage(@"Page8", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("\"Enter, then, and look,\" said Father Wolf stiffly, \"but there");
		yield return lineBreak();
		yield return text("is no food here.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page9", "Page9", null);
		yield break;
	}


	// .............
	// #9: Page9

	void passage9_Init()
	{
		this.Passages[@"Page9"] = new StoryPassage(@"Page9", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("\"For a wolf, no,\" said Tabaqui, \"but for so mean a person as");
		yield return lineBreak();
		yield return text("myself a dry bone is a good feast.  Who are we, the Gidur-log ");
		using (Group("hook", "")) {
			yield return text("the");
			yield return lineBreak();
			yield return text("jackal people");
		}
		yield return text(", to pick and choose?\"  He scuttled to the back of");
		yield return lineBreak();
		yield return text("the cave, where he found the bone of a buck with some meat on it,");
		yield return lineBreak();
		yield return text("and sat cracking the end merrily.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page10", "Page10", null);
		yield break;
	}


	// .............
	// #10: Page10

	void passage10_Init()
	{
		this.Passages[@"Page10"] = new StoryPassage(@"Page10", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("\"All thanks for this good meal,\" he said, licking his lips.");
		yield return lineBreak();
		yield return text("\"How beautiful are the noble children!  How large are their eyes!");
		yield return lineBreak();
		yield return text("And so young too!  Indeed, indeed, I might have remembered that");
		yield return lineBreak();
		yield return text("the children of kings are men from the beginning.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page11", "Page11", null);
		yield break;
	}


	// .............
	// #11: Page11

	void passage11_Init()
	{
		this.Passages[@"Page11"] = new StoryPassage(@"Page11", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("Now, Tabaqui knew as well as anyone else that there is nothing");
		yield return lineBreak();
		yield return text("so unlucky as to compliment children to their faces.  It pleased");
		yield return lineBreak();
		yield return text("him to see Mother and Father Wolf look uncomfortable.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page12", "Page12", null);
		yield break;
	}


	// .............
	// #12: Page12

	void passage12_Init()
	{
		this.Passages[@"Page12"] = new StoryPassage(@"Page12", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("Tabaqui sat still, rejoicing in the mischief that he had made,");
		yield return lineBreak();
		yield return text("and then he said spitefully:");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page13", "Page13", null);
		yield break;
	}


	// .............
	// #13: Page13

	void passage13_Init()
	{
		this.Passages[@"Page13"] = new StoryPassage(@"Page13", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("\"Shere Khan, the Big One, has shifted his hunting grounds.  He");
		yield return lineBreak();
		yield return text("will hunt among these hills for the next moon, so he has told me.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page14", "Page14", null);
		yield break;
	}


	// .............
	// #14: Page14

	void passage14_Init()
	{
		this.Passages[@"Page14"] = new StoryPassage(@"Page14", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("Shere Khan was the tiger who lived near the Waingunga River,");
		yield return lineBreak();
		yield return text("twenty miles away.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page15", "Page15", null);
		yield break;
	}


	// .............
	// #15: Page15

	void passage15_Init()
	{
		this.Passages[@"Page15"] = new StoryPassage(@"Page15", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("\"He has no right!\" Father Wolf began angrily--\"By the Law");
		yield return lineBreak();
		yield return text("of the Jungle he has no right to change his quarters without due");
		yield return lineBreak();
		yield return text("warning.  He will frighten every head of game within ten miles,");
		yield return lineBreak();
		yield return text("and I--I have to kill for two, these days.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page16", "Page16", null);
		yield break;
	}


	// .............
	// #16: Page16

	void passage16_Init()
	{
		this.Passages[@"Page16"] = new StoryPassage(@"Page16", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("\"His mother did not call him Lungri ");
		using (Group("hook", "")) {
			yield return text("the Lame One");
		}
		yield return text(" for");
		yield return lineBreak();
		yield return text("nothing,\" said Mother Wolf quietly.  \"He has been lame in one foot");
		yield return lineBreak();
		yield return text("from his birth.  That is why he has only killed cattle.  Now the");
		yield return lineBreak();
		yield return text("villagers of the Waingunga are angry with him, and he has come");
		yield return lineBreak();
		yield return text("here to make our villagers angry. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page17", "Page17", null);
		yield break;
	}


	// .............
	// #17: Page17

	void passage17_Init()
	{
		this.Passages[@"Page17"] = new StoryPassage(@"Page17", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("They will scour the jungle for");
		yield return lineBreak();
		yield return text("him when he is far away, and we and our children must run when the");
		yield return lineBreak();
		yield return text("grass is set alight.  Indeed, we are very grateful to Shere Khan!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page18", "Page18", null);
		yield break;
	}


	// .............
	// #18: Page18

	void passage18_Init()
	{
		this.Passages[@"Page18"] = new StoryPassage(@"Page18", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("\"Shall I tell him of your gratitude?\" said Tabaqui.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page19", "Page19", null);
		yield break;
	}


	// .............
	// #19: Page19

	void passage19_Init()
	{
		this.Passages[@"Page19"] = new StoryPassage(@"Page19", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("\"Out!\" snapped Father Wolf.  \"Out and hunt with thy master.");
		yield return lineBreak();
		yield return text("Thou hast done harm enough for one night.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page20", "Page20", null);
		yield break;
	}


	// .............
	// #20: Page20

	void passage20_Init()
	{
		this.Passages[@"Page20"] = new StoryPassage(@"Page20", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("\"I go,\" said Tabaqui quietly.  \"Ye can hear Shere Khan below");
		yield return lineBreak();
		yield return text("in the thickets.  I might have saved myself the message.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page21", "Page21", null);
		yield break;
	}


	// .............
	// #21: Page21

	void passage21_Init()
	{
		this.Passages[@"Page21"] = new StoryPassage(@"Page21", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text("Father Wolf listened, and below in the valley that ran down to");
		yield return lineBreak();
		yield return text("a little river he heard the dry, angry, snarly, singsong whine of");
		yield return lineBreak();
		yield return text("a tiger who has caught nothing and does not care if all the jungle");
		yield return lineBreak();
		yield return text("knows it.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page22", "Page22", null);
		yield break;
	}


	// .............
	// #22: Page22

	void passage22_Init()
	{
		this.Passages[@"Page22"] = new StoryPassage(@"Page22", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text("\"The fool!\" said Father Wolf.  \"To begin a night's work with");
		yield return lineBreak();
		yield return text("that noise!  Does he think that our buck are like his him?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page23", "Page23", null);
		yield break;
	}


	// .............
	// #23: Page23

	void passage23_Init()
	{
		this.Passages[@"Page23"] = new StoryPassage(@"Page23", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text("\"H'sh.  It is neither bullock nor buck he hunts to-night,\"");
		yield return lineBreak();
		yield return text("said Mother Wolf.  \"It is Man.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page24", "Page24", null);
		yield break;
	}


	// .............
	// #24: Page24

	void passage24_Init()
	{
		this.Passages[@"Page24"] = new StoryPassage(@"Page24", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		yield return text("The whine had changed to a sort of humming purr that seemed to");
		yield return lineBreak();
		yield return text("come from every quarter of the compass.  It was the noise that");
		yield return lineBreak();
		yield return text("bewilders woodcutters and gypsies sleeping in the open, and makes");
		yield return lineBreak();
		yield return text("them run sometimes into the very mouth of the tiger.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page25", "Page25", null);
		yield break;
	}


	// .............
	// #25: Page25

	void passage25_Init()
	{
		this.Passages[@"Page25"] = new StoryPassage(@"Page25", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		yield return text("\"Man!\" said Father Wolf, showing all his white teeth.  \"Faugh!");
		yield return lineBreak();
		yield return text("Are there not enough beetles and frogs in the tanks that he must");
		yield return lineBreak();
		yield return text("eat Man, and on our ground too!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page26", "Page26", null);
		yield break;
	}


	// .............
	// #26: Page26

	void passage26_Init()
	{
		this.Passages[@"Page26"] = new StoryPassage(@"Page26", new string[]{  }, passage26_Main);
	}

	IStoryThread passage26_Main()
	{
		yield return text("The Law of the Jungle, which never orders anything without a");
		yield return lineBreak();
		yield return text("reason, forbids every beast to eat Man except when he is killing");
		yield return lineBreak();
		yield return text("to show his children how to kill, and then he must hunt outside");
		yield return lineBreak();
		yield return text("the hunting grounds of his pack or tribe.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page27", "Page27", null);
		yield break;
	}


	// .............
	// #27: Page27

	void passage27_Init()
	{
		this.Passages[@"Page27"] = new StoryPassage(@"Page27", new string[]{  }, passage27_Main);
	}

	IStoryThread passage27_Main()
	{
		yield return text("The real reason for this is that man-killing means, sooner or later, the arrival of white men on elephants, with guns, and hundreds of brown men with gongs and rockets and torches.  Then everybody in the jungle");
		yield return lineBreak();
		yield return text("suffers. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page28", "Page28", null);
		yield break;
	}


	// .............
	// #28: Page28

	void passage28_Init()
	{
		this.Passages[@"Page28"] = new StoryPassage(@"Page28", new string[]{  }, passage28_Main);
	}

	IStoryThread passage28_Main()
	{
		yield return text("The reason the beasts give among themselves is that Man");
		yield return lineBreak();
		yield return text("is the weakest and most defenseless of all living things, and it");
		yield return lineBreak();
		yield return text("is unsportsmanlike to touch him.  They say too--and it is true");
		yield return lineBreak();
		yield return text("--that man-eaters become mangy, and lose their teeth.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page29", "Page29", null);
		yield break;
	}


	// .............
	// #29: Page29

	void passage29_Init()
	{
		this.Passages[@"Page29"] = new StoryPassage(@"Page29", new string[]{  }, passage29_Main);
	}

	IStoryThread passage29_Main()
	{
		yield return text("The purr grew louder, and ended in the full-throated \"Aaarh!\"");
		yield return lineBreak();
		yield return text("of the tiger's charge.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page30", "Page30", null);
		yield break;
	}


	// .............
	// #30: Page30

	void passage30_Init()
	{
		this.Passages[@"Page30"] = new StoryPassage(@"Page30", new string[]{  }, passage30_Main);
	}

	IStoryThread passage30_Main()
	{
		yield return text("Then there was a howl--an untigerish howl--from Shere");
		yield return lineBreak();
		yield return text("Khan.  \"He has missed,\" said Mother Wolf.  \"What is it?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page31", "Page31", null);
		yield break;
	}


	// .............
	// #31: Page31

	void passage31_Init()
	{
		this.Passages[@"Page31"] = new StoryPassage(@"Page31", new string[]{  }, passage31_Main);
	}

	IStoryThread passage31_Main()
	{
		yield return text("Father Wolf ran out a few paces and heard Shere Khan muttering");
		yield return lineBreak();
		yield return text("and mumbling savagely as he tumbled about in the scrub.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page32", "Page32", null);
		yield break;
	}


	// .............
	// #32: Page32

	void passage32_Init()
	{
		this.Passages[@"Page32"] = new StoryPassage(@"Page32", new string[]{  }, passage32_Main);
	}

	IStoryThread passage32_Main()
	{
		yield return text("\"The fool has had no more sense than to jump at a woodcutter's");
		yield return lineBreak();
		yield return text("campfire, and has burned his feet,\" said Father Wolf with a grunt.");
		yield return lineBreak();
		yield return text("\"Tabaqui is with him.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page33", "Page33", null);
		yield break;
	}


	// .............
	// #33: Page33

	void passage33_Init()
	{
		this.Passages[@"Page33"] = new StoryPassage(@"Page33", new string[]{  }, passage33_Main);
	}

	IStoryThread passage33_Main()
	{
		yield return text("\"Something is coming uphill,\" said Mother Wolf, twitching one");
		yield return lineBreak();
		yield return text("ear.  \"Get ready.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page34", "Page34", null);
		yield break;
	}


	// .............
	// #34: Page34

	void passage34_Init()
	{
		this.Passages[@"Page34"] = new StoryPassage(@"Page34", new string[]{  }, passage34_Main);
	}

	IStoryThread passage34_Main()
	{
		yield return text("The bushes rustled a little in the thicket, and Father Wolf");
		yield return lineBreak();
		yield return text("dropped with his haunches under him, ready for his leap.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page35", "Page35", null);
		yield break;
	}


	// .............
	// #35: Page35

	void passage35_Init()
	{
		this.Passages[@"Page35"] = new StoryPassage(@"Page35", new string[]{  }, passage35_Main);
	}

	IStoryThread passage35_Main()
	{
		yield return text("Then, if");
		yield return lineBreak();
		yield return text("you had been watching, you would have seen the most wonderful");
		yield return lineBreak();
		yield return text("thing in the world--the wolf checked in mid-spring.  He made his");
		yield return lineBreak();
		yield return text("bound before he saw what it was he was jumping at, and then he");
		yield return lineBreak();
		yield return text("tried to stop himself. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page36", "Page36", null);
		yield break;
	}


	// .............
	// #36: Page36

	void passage36_Init()
	{
		this.Passages[@"Page36"] = new StoryPassage(@"Page36", new string[]{  }, passage36_Main);
	}

	IStoryThread passage36_Main()
	{
		yield return text("The result was that he shot up straight");
		yield return lineBreak();
		yield return text("into the air for four or five feet, landing almost where he left");
		yield return lineBreak();
		yield return text("ground.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page37", "Page37", null);
		yield break;
	}


	// .............
	// #37: Page37

	void passage37_Init()
	{
		this.Passages[@"Page37"] = new StoryPassage(@"Page37", new string[]{  }, passage37_Main);
	}

	IStoryThread passage37_Main()
	{
		yield return text("\"Man!\" he snapped.  \"A man's cub.  Look!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page38", "Page38", null);
		yield break;
	}


	// .............
	// #38: Page38

	void passage38_Init()
	{
		this.Passages[@"Page38"] = new StoryPassage(@"Page38", new string[]{  }, passage38_Main);
	}

	IStoryThread passage38_Main()
	{
		yield return text("Directly in front of him, holding on by a low branch, stood a");
		yield return lineBreak();
		yield return text("naked brown baby who could just walk--as soft and as dimpled a");
		yield return lineBreak();
		yield return text("little atom as ever came to a wolf's cave at night.  He looked up");
		yield return lineBreak();
		yield return text("into Father Wolf's face, and laughed.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page39", "Page39", null);
		yield break;
	}


	// .............
	// #39: Page39

	void passage39_Init()
	{
		this.Passages[@"Page39"] = new StoryPassage(@"Page39", new string[]{  }, passage39_Main);
	}

	IStoryThread passage39_Main()
	{
		yield return text("\"Is that a man's cub?\" said Mother Wolf.  \"I have never seen");
		yield return lineBreak();
		yield return text("one.  Bring it here.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page40", "Page40", null);
		yield break;
	}


	// .............
	// #40: Page40

	void passage40_Init()
	{
		this.Passages[@"Page40"] = new StoryPassage(@"Page40", new string[]{  }, passage40_Main);
	}

	IStoryThread passage40_Main()
	{
		yield return text("A Wolf accustomed to moving his own cubs can, if necessary,");
		yield return lineBreak();
		yield return text("mouth an egg without breaking it, and though Father Wolf's jaws");
		yield return lineBreak();
		yield return text("closed right on the child's back not a tooth even scratched the");
		yield return lineBreak();
		yield return text("skin as he laid it down among the cubs.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page41", "Page41", null);
		yield break;
	}


	// .............
	// #41: Page41

	void passage41_Init()
	{
		this.Passages[@"Page41"] = new StoryPassage(@"Page41", new string[]{  }, passage41_Main);
	}

	IStoryThread passage41_Main()
	{
		yield return text("\"How little!  How naked, and--how bold!\" said Mother Wolf");
		yield return lineBreak();
		yield return text("softly.  The baby was pushing his way between the cubs to get");
		yield return lineBreak();
		yield return text("close to the warm hide. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page42", "Page42", null);
		yield break;
	}


	// .............
	// #42: Page42

	void passage42_Init()
	{
		this.Passages[@"Page42"] = new StoryPassage(@"Page42", new string[]{  }, passage42_Main);
	}

	IStoryThread passage42_Main()
	{
		yield return text("\"Ahai!  He is taking his meal with the");
		yield return lineBreak();
		yield return text("others.  And so this is a man's cub.  Now, was there ever a wolf");
		yield return lineBreak();
		yield return text("that could boast of a man's cub among her children?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page43", "Page43", null);
		yield break;
	}


	// .............
	// #43: Page43

	void passage43_Init()
	{
		this.Passages[@"Page43"] = new StoryPassage(@"Page43", new string[]{  }, passage43_Main);
	}

	IStoryThread passage43_Main()
	{
		yield return text("\"I have heard now and again of such a thing, but never in our");
		yield return lineBreak();
		yield return text("Pack or in my time,\" said Father Wolf. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page44", "Page44", null);
		yield break;
	}


	// .............
	// #44: Page44

	void passage44_Init()
	{
		this.Passages[@"Page44"] = new StoryPassage(@"Page44", new string[]{  }, passage44_Main);
	}

	IStoryThread passage44_Main()
	{
		yield return text("\"He is altogether without");
		yield return lineBreak();
		yield return text("hair, and I could kill him with a touch of my foot.  But see, he");
		yield return lineBreak();
		yield return text("looks up and is not afraid.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page45", "Page45", null);
		yield break;
	}


	// .............
	// #45: Page45

	void passage45_Init()
	{
		this.Passages[@"Page45"] = new StoryPassage(@"Page45", new string[]{  }, passage45_Main);
	}

	IStoryThread passage45_Main()
	{
		yield return text("The moonlight was blocked out of the mouth of the cave, for");
		yield return lineBreak();
		yield return text("Shere Khan's great square head and shoulders were thrust into the");
		yield return lineBreak();
		yield return text("entrance.  Tabaqui, behind him, was squeaking: \"My lord, my lord,");
		yield return lineBreak();
		yield return text("it went in here!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page46", "Page46", null);
		yield break;
	}


	// .............
	// #46: Page46

	void passage46_Init()
	{
		this.Passages[@"Page46"] = new StoryPassage(@"Page46", new string[]{  }, passage46_Main);
	}

	IStoryThread passage46_Main()
	{
		yield return text("\"Shere Khan does us great honor,\" said Father Wolf, but his");
		yield return lineBreak();
		yield return text("eyes were very angry.  \"What does Shere Khan need?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page47", "Page47", null);
		yield break;
	}


	// .............
	// #47: Page47

	void passage47_Init()
	{
		this.Passages[@"Page47"] = new StoryPassage(@"Page47", new string[]{  }, passage47_Main);
	}

	IStoryThread passage47_Main()
	{
		yield return text("\"My quarry.  A man's cub went this way,\" said Shere Khan.");
		yield return lineBreak();
		yield return text("\"Its parents have run off.  Give it to me.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page48", "Page48", null);
		yield break;
	}


	// .............
	// #48: Page48

	void passage48_Init()
	{
		this.Passages[@"Page48"] = new StoryPassage(@"Page48", new string[]{  }, passage48_Main);
	}

	IStoryThread passage48_Main()
	{
		yield return text("Shere Khan had jumped at a woodcutter's campfire, as Father");
		yield return lineBreak();
		yield return text("Wolf had said, and was furious from the pain of his burned feet.");
		yield return lineBreak();
		yield return text("But Father Wolf knew that the mouth of the cave was too narrow for");
		yield return lineBreak();
		yield return text("a tiger to come in by. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page49", "Page49", null);
		yield break;
	}


	// .............
	// #49: Page49

	void passage49_Init()
	{
		this.Passages[@"Page49"] = new StoryPassage(@"Page49", new string[]{  }, passage49_Main);
	}

	IStoryThread passage49_Main()
	{
		yield return text("Even where he was, Shere Khan's shoulders");
		yield return lineBreak();
		yield return text("and forepaws were cramped for want of room, as a man's would be if");
		yield return lineBreak();
		yield return text("he tried to fight in a barrel.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page50", "Page50", null);
		yield break;
	}


	// .............
	// #50: Page50

	void passage50_Init()
	{
		this.Passages[@"Page50"] = new StoryPassage(@"Page50", new string[]{  }, passage50_Main);
	}

	IStoryThread passage50_Main()
	{
		yield return text("\"The Wolves are a free people,\" said Father Wolf.  \"They take");
		yield return lineBreak();
		yield return text("orders from the Head of the Pack, and not from any striped");
		yield return lineBreak();
		yield return text("cattle-killer.  The man's cub is ours--to kill if we choose.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page51", "Page51", null);
		yield break;
	}


	// .............
	// #51: Page51

	void passage51_Init()
	{
		this.Passages[@"Page51"] = new StoryPassage(@"Page51", new string[]{  }, passage51_Main);
	}

	IStoryThread passage51_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}