/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: chap1_part1.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @chap1_part1: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@chap1_part1()
	{
		this.StartPassage = "Chapter 1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
		passage26_Init();
		passage27_Init();
		passage28_Init();
		passage29_Init();
		passage30_Init();
		passage31_Init();
		passage32_Init();
		passage33_Init();
		passage34_Init();
		passage35_Init();
		passage36_Init();
		passage37_Init();
		passage38_Init();
		passage39_Init();
		passage40_Init();
		passage41_Init();
		passage42_Init();
		passage43_Init();
		passage44_Init();
		passage45_Init();
		passage46_Init();
		passage47_Init();
		passage48_Init();
		passage49_Init();
		passage50_Init();
		passage51_Init();
		passage52_Init();
		passage53_Init();
		passage54_Init();
		passage55_Init();
		passage56_Init();
		passage57_Init();
		passage58_Init();
		passage59_Init();
		passage60_Init();
		passage61_Init();
		passage62_Init();
		passage63_Init();
		passage64_Init();
		passage65_Init();
		passage66_Init();
		passage67_Init();
		passage68_Init();
		passage69_Init();
		passage70_Init();
		passage71_Init();
		passage72_Init();
		passage73_Init();
		passage74_Init();
		passage75_Init();
		passage76_Init();
		passage77_Init();
		passage78_Init();
		passage79_Init();
		passage80_Init();
		passage81_Init();
		passage82_Init();
		passage83_Init();
		passage84_Init();
		passage85_Init();
		passage86_Init();
		passage87_Init();
		passage88_Init();
		passage89_Init();
		passage90_Init();
		passage91_Init();
		passage92_Init();
		passage93_Init();
		passage94_Init();
		passage95_Init();
		passage96_Init();
		passage97_Init();
		passage98_Init();
		passage99_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Chapter 1

	void passage1_Init()
	{
		this.Passages[@"Chapter 1"] = new StoryPassage(@"Chapter 1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Now Rann the Kite brings home the night");
		yield return lineBreak();
		yield return text("      That Mang the Bat sets free--");
		yield return lineBreak();
		yield return text("   The herds are shut in byre and hut");
		yield return lineBreak();
		yield return text("      For loosed till dawn are we.");
		yield return lineBreak();
		yield return text("   This is the hour of pride and power,");
		yield return lineBreak();
		yield return text("      Talon and tush and claw.");
		yield return lineBreak();
		yield return text("   Oh, hear the call!--Good hunting all");
		yield return lineBreak();
		yield return text("      That keep the Jungle Law!");
		yield return lineBreak();
		yield return text("   Night-Song in the Jungle");
		yield return lineBreak();
		yield return text("   ");
		yield return lineBreak();
		yield return text("   ");
		yield return link("Page2", "Page2", null);
		yield break;
	}


	// .............
	// #2: Page2

	void passage2_Init()
	{
		this.Passages[@"Page2"] = new StoryPassage(@"Page2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("It was seven o'clock of a very warm evening in the Seeonee hills");
		yield return lineBreak();
		yield return text("when Father Wolf woke up from his day's rest, scratched himself,");
		yield return lineBreak();
		yield return text("yawned, and spread out his paws one after the other to get rid of");
		yield return lineBreak();
		yield return text("the sleepy feeling in their tips.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page3", "Page3", null);
		yield break;
	}


	// .............
	// #3: Page3

	void passage3_Init()
	{
		this.Passages[@"Page3"] = new StoryPassage(@"Page3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Mother Wolf lay with her big");
		yield return lineBreak();
		yield return text("gray nose dropped across her four tumbling, squealing cubs, and");
		yield return lineBreak();
		yield return text("the moon shone into the mouth of the cave where they all lived.");
		yield return lineBreak();
		yield return text("\"Augrh!\" said Father Wolf.  \"It is time to hunt again.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page4", "Page4", null);
		yield break;
	}


	// .............
	// #4: Page4

	void passage4_Init()
	{
		this.Passages[@"Page4"] = new StoryPassage(@"Page4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("He was going to spring down hill when a little shadow with a bushy tail");
		yield return lineBreak();
		yield return text("crossed the threshold and whined: \"Good luck go with you, O Chief");
		yield return lineBreak();
		yield return text("of the Wolves.  And good luck and strong white teeth go with noble");
		yield return lineBreak();
		yield return text("children that they may never forget the hungry in this world.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page5", "Page5", null);
		yield break;
	}


	// .............
	// #5: Page5

	void passage5_Init()
	{
		this.Passages[@"Page5"] = new StoryPassage(@"Page5", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("It was the jackal--Tabaqui, the Dish-licker--and the");
		yield return lineBreak();
		yield return text("wolves of India despise Tabaqui because he runs about making");
		yield return lineBreak();
		yield return text("mischief, and telling tales, and eating rags and pieces of leather");
		yield return lineBreak();
		yield return text("from the village rubbish-heaps.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page6", "Page6", null);
		yield break;
	}


	// .............
	// #6: Page6

	void passage6_Init()
	{
		this.Passages[@"Page6"] = new StoryPassage(@"Page6", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("But they are afraid of him too,");
		yield return lineBreak();
		yield return text("because Tabaqui, more than anyone else in the jungle, is apt to go");
		yield return lineBreak();
		yield return text("mad, and then he forgets that he was ever afraid of anyone, and");
		yield return lineBreak();
		yield return text("runs through the forest biting everything in his way.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page7", "Page7", null);
		yield break;
	}


	// .............
	// #7: Page7

	void passage7_Init()
	{
		this.Passages[@"Page7"] = new StoryPassage(@"Page7", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Even the tiger runs and hides when little Tabaqui goes mad, for madness is");
		yield return lineBreak();
		yield return text("the most disgraceful thing that can overtake a wild creature.  We");
		yield return lineBreak();
		yield return text("call it hydrophobia, but they call it dewanee--the madness--");
		yield return lineBreak();
		yield return text("and run.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page8", "Page8", null);
		yield break;
	}


	// .............
	// #8: Page8

	void passage8_Init()
	{
		this.Passages[@"Page8"] = new StoryPassage(@"Page8", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("\"Enter, then, and look,\" said Father Wolf stiffly, \"but there");
		yield return lineBreak();
		yield return text("is no food here.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page9", "Page9", null);
		yield break;
	}


	// .............
	// #9: Page9

	void passage9_Init()
	{
		this.Passages[@"Page9"] = new StoryPassage(@"Page9", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("\"For a wolf, no,\" said Tabaqui, \"but for so mean a person as");
		yield return lineBreak();
		yield return text("myself a dry bone is a good feast.  Who are we, the Gidur-log ");
		using (Group("hook", "")) {
			yield return text("the");
			yield return lineBreak();
			yield return text("jackal people");
		}
		yield return text(", to pick and choose?\"  He scuttled to the back of");
		yield return lineBreak();
		yield return text("the cave, where he found the bone of a buck with some meat on it,");
		yield return lineBreak();
		yield return text("and sat cracking the end merrily.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page10", "Page10", null);
		yield break;
	}


	// .............
	// #10: Page10

	void passage10_Init()
	{
		this.Passages[@"Page10"] = new StoryPassage(@"Page10", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("\"All thanks for this good meal,\" he said, licking his lips.");
		yield return lineBreak();
		yield return text("\"How beautiful are the noble children!  How large are their eyes!");
		yield return lineBreak();
		yield return text("And so young too!  Indeed, indeed, I might have remembered that");
		yield return lineBreak();
		yield return text("the children of kings are men from the beginning.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page11", "Page11", null);
		yield break;
	}


	// .............
	// #11: Page11

	void passage11_Init()
	{
		this.Passages[@"Page11"] = new StoryPassage(@"Page11", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("Now, Tabaqui knew as well as anyone else that there is nothing");
		yield return lineBreak();
		yield return text("so unlucky as to compliment children to their faces.  It pleased");
		yield return lineBreak();
		yield return text("him to see Mother and Father Wolf look uncomfortable.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page12", "Page12", null);
		yield break;
	}


	// .............
	// #12: Page12

	void passage12_Init()
	{
		this.Passages[@"Page12"] = new StoryPassage(@"Page12", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("Tabaqui sat still, rejoicing in the mischief that he had made,");
		yield return lineBreak();
		yield return text("and then he said spitefully:");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page13", "Page13", null);
		yield break;
	}


	// .............
	// #13: Page13

	void passage13_Init()
	{
		this.Passages[@"Page13"] = new StoryPassage(@"Page13", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("\"Shere Khan, the Big One, has shifted his hunting grounds.  He");
		yield return lineBreak();
		yield return text("will hunt among these hills for the next moon, so he has told me.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page14", "Page14", null);
		yield break;
	}


	// .............
	// #14: Page14

	void passage14_Init()
	{
		this.Passages[@"Page14"] = new StoryPassage(@"Page14", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("Shere Khan was the tiger who lived near the Waingunga River,");
		yield return lineBreak();
		yield return text("twenty miles away.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page15", "Page15", null);
		yield break;
	}


	// .............
	// #15: Page15

	void passage15_Init()
	{
		this.Passages[@"Page15"] = new StoryPassage(@"Page15", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("\"He has no right!\" Father Wolf began angrily--\"By the Law");
		yield return lineBreak();
		yield return text("of the Jungle he has no right to change his quarters without due");
		yield return lineBreak();
		yield return text("warning.  He will frighten every head of game within ten miles,");
		yield return lineBreak();
		yield return text("and I--I have to kill for two, these days.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page16", "Page16", null);
		yield break;
	}


	// .............
	// #16: Page16

	void passage16_Init()
	{
		this.Passages[@"Page16"] = new StoryPassage(@"Page16", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("\"His mother did not call him Lungri ");
		using (Group("hook", "")) {
			yield return text("the Lame One");
		}
		yield return text(" for");
		yield return lineBreak();
		yield return text("nothing,\" said Mother Wolf quietly.  \"He has been lame in one foot");
		yield return lineBreak();
		yield return text("from his birth.  That is why he has only killed cattle.  Now the");
		yield return lineBreak();
		yield return text("villagers of the Waingunga are angry with him, and he has come");
		yield return lineBreak();
		yield return text("here to make our villagers angry. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page17", "Page17", null);
		yield break;
	}


	// .............
	// #17: Page17

	void passage17_Init()
	{
		this.Passages[@"Page17"] = new StoryPassage(@"Page17", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("They will scour the jungle for");
		yield return lineBreak();
		yield return text("him when he is far away, and we and our children must run when the");
		yield return lineBreak();
		yield return text("grass is set alight.  Indeed, we are very grateful to Shere Khan!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page18", "Page18", null);
		yield break;
	}


	// .............
	// #18: Page18

	void passage18_Init()
	{
		this.Passages[@"Page18"] = new StoryPassage(@"Page18", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("\"Shall I tell him of your gratitude?\" said Tabaqui.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page19", "Page19", null);
		yield break;
	}


	// .............
	// #19: Page19

	void passage19_Init()
	{
		this.Passages[@"Page19"] = new StoryPassage(@"Page19", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("\"Out!\" snapped Father Wolf.  \"Out and hunt with thy master.");
		yield return lineBreak();
		yield return text("Thou hast done harm enough for one night.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page20", "Page20", null);
		yield break;
	}


	// .............
	// #20: Page20

	void passage20_Init()
	{
		this.Passages[@"Page20"] = new StoryPassage(@"Page20", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("\"I go,\" said Tabaqui quietly.  \"Ye can hear Shere Khan below");
		yield return lineBreak();
		yield return text("in the thickets.  I might have saved myself the message.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page21", "Page21", null);
		yield break;
	}


	// .............
	// #21: Page21

	void passage21_Init()
	{
		this.Passages[@"Page21"] = new StoryPassage(@"Page21", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text("Father Wolf listened, and below in the valley that ran down to");
		yield return lineBreak();
		yield return text("a little river he heard the dry, angry, snarly, singsong whine of");
		yield return lineBreak();
		yield return text("a tiger who has caught nothing and does not care if all the jungle");
		yield return lineBreak();
		yield return text("knows it.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page22", "Page22", null);
		yield break;
	}


	// .............
	// #22: Page22

	void passage22_Init()
	{
		this.Passages[@"Page22"] = new StoryPassage(@"Page22", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text("\"The fool!\" said Father Wolf.  \"To begin a night's work with");
		yield return lineBreak();
		yield return text("that noise!  Does he think that our buck are like his him?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page23", "Page23", null);
		yield break;
	}


	// .............
	// #23: Page23

	void passage23_Init()
	{
		this.Passages[@"Page23"] = new StoryPassage(@"Page23", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text("\"H'sh.  It is neither bullock nor buck he hunts to-night,\"");
		yield return lineBreak();
		yield return text("said Mother Wolf.  \"It is Man.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page24", "Page24", null);
		yield break;
	}


	// .............
	// #24: Page24

	void passage24_Init()
	{
		this.Passages[@"Page24"] = new StoryPassage(@"Page24", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		yield return text("The whine had changed to a sort of humming purr that seemed to");
		yield return lineBreak();
		yield return text("come from every quarter of the compass.  It was the noise that");
		yield return lineBreak();
		yield return text("bewilders woodcutters and gypsies sleeping in the open, and makes");
		yield return lineBreak();
		yield return text("them run sometimes into the very mouth of the tiger.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page25", "Page25", null);
		yield break;
	}


	// .............
	// #25: Page25

	void passage25_Init()
	{
		this.Passages[@"Page25"] = new StoryPassage(@"Page25", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		yield return text("\"Man!\" said Father Wolf, showing all his white teeth.  \"Faugh!");
		yield return lineBreak();
		yield return text("Are there not enough beetles and frogs in the tanks that he must");
		yield return lineBreak();
		yield return text("eat Man, and on our ground too!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page26", "Page26", null);
		yield break;
	}


	// .............
	// #26: Page26

	void passage26_Init()
	{
		this.Passages[@"Page26"] = new StoryPassage(@"Page26", new string[]{  }, passage26_Main);
	}

	IStoryThread passage26_Main()
	{
		yield return text("The Law of the Jungle, which never orders anything without a");
		yield return lineBreak();
		yield return text("reason, forbids every beast to eat Man except when he is killing");
		yield return lineBreak();
		yield return text("to show his children how to kill, and then he must hunt outside");
		yield return lineBreak();
		yield return text("the hunting grounds of his pack or tribe.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page27", "Page27", null);
		yield break;
	}


	// .............
	// #27: Page27

	void passage27_Init()
	{
		this.Passages[@"Page27"] = new StoryPassage(@"Page27", new string[]{  }, passage27_Main);
	}

	IStoryThread passage27_Main()
	{
		yield return text("The real reason for this is that man-killing means, sooner or later, the arrival of white men on elephants, with guns, and hundreds of brown men with gongs and rockets and torches.  Then everybody in the jungle");
		yield return lineBreak();
		yield return text("suffers. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page28", "Page28", null);
		yield break;
	}


	// .............
	// #28: Page28

	void passage28_Init()
	{
		this.Passages[@"Page28"] = new StoryPassage(@"Page28", new string[]{  }, passage28_Main);
	}

	IStoryThread passage28_Main()
	{
		yield return text("The reason the beasts give among themselves is that Man");
		yield return lineBreak();
		yield return text("is the weakest and most defenseless of all living things, and it");
		yield return lineBreak();
		yield return text("is unsportsmanlike to touch him.  They say too--and it is true");
		yield return lineBreak();
		yield return text("--that man-eaters become mangy, and lose their teeth.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page29", "Page29", null);
		yield break;
	}


	// .............
	// #29: Page29

	void passage29_Init()
	{
		this.Passages[@"Page29"] = new StoryPassage(@"Page29", new string[]{  }, passage29_Main);
	}

	IStoryThread passage29_Main()
	{
		yield return text("The purr grew louder, and ended in the full-throated \"Aaarh!\"");
		yield return lineBreak();
		yield return text("of the tiger's charge.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page30", "Page30", null);
		yield break;
	}


	// .............
	// #30: Page30

	void passage30_Init()
	{
		this.Passages[@"Page30"] = new StoryPassage(@"Page30", new string[]{  }, passage30_Main);
	}

	IStoryThread passage30_Main()
	{
		yield return text("Then there was a howl--an untigerish howl--from Shere");
		yield return lineBreak();
		yield return text("Khan.  \"He has missed,\" said Mother Wolf.  \"What is it?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page31", "Page31", null);
		yield break;
	}


	// .............
	// #31: Page31

	void passage31_Init()
	{
		this.Passages[@"Page31"] = new StoryPassage(@"Page31", new string[]{  }, passage31_Main);
	}

	IStoryThread passage31_Main()
	{
		yield return text("Father Wolf ran out a few paces and heard Shere Khan muttering");
		yield return lineBreak();
		yield return text("and mumbling savagely as he tumbled about in the scrub.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page32", "Page32", null);
		yield break;
	}


	// .............
	// #32: Page32

	void passage32_Init()
	{
		this.Passages[@"Page32"] = new StoryPassage(@"Page32", new string[]{  }, passage32_Main);
	}

	IStoryThread passage32_Main()
	{
		yield return text("\"The fool has had no more sense than to jump at a woodcutter's");
		yield return lineBreak();
		yield return text("campfire, and has burned his feet,\" said Father Wolf with a grunt.");
		yield return lineBreak();
		yield return text("\"Tabaqui is with him.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page33", "Page33", null);
		yield break;
	}


	// .............
	// #33: Page33

	void passage33_Init()
	{
		this.Passages[@"Page33"] = new StoryPassage(@"Page33", new string[]{  }, passage33_Main);
	}

	IStoryThread passage33_Main()
	{
		yield return text("\"Something is coming uphill,\" said Mother Wolf, twitching one");
		yield return lineBreak();
		yield return text("ear.  \"Get ready.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page34", "Page34", null);
		yield break;
	}


	// .............
	// #34: Page34

	void passage34_Init()
	{
		this.Passages[@"Page34"] = new StoryPassage(@"Page34", new string[]{  }, passage34_Main);
	}

	IStoryThread passage34_Main()
	{
		yield return text("The bushes rustled a little in the thicket, and Father Wolf");
		yield return lineBreak();
		yield return text("dropped with his haunches under him, ready for his leap.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page35", "Page35", null);
		yield break;
	}


	// .............
	// #35: Page35

	void passage35_Init()
	{
		this.Passages[@"Page35"] = new StoryPassage(@"Page35", new string[]{  }, passage35_Main);
	}

	IStoryThread passage35_Main()
	{
		yield return text("Then, if");
		yield return lineBreak();
		yield return text("you had been watching, you would have seen the most wonderful");
		yield return lineBreak();
		yield return text("thing in the world--the wolf checked in mid-spring.  He made his");
		yield return lineBreak();
		yield return text("bound before he saw what it was he was jumping at, and then he");
		yield return lineBreak();
		yield return text("tried to stop himself. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page36", "Page36", null);
		yield break;
	}


	// .............
	// #36: Page36

	void passage36_Init()
	{
		this.Passages[@"Page36"] = new StoryPassage(@"Page36", new string[]{  }, passage36_Main);
	}

	IStoryThread passage36_Main()
	{
		yield return text("The result was that he shot up straight");
		yield return lineBreak();
		yield return text("into the air for four or five feet, landing almost where he left");
		yield return lineBreak();
		yield return text("ground.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page37", "Page37", null);
		yield break;
	}


	// .............
	// #37: Page37

	void passage37_Init()
	{
		this.Passages[@"Page37"] = new StoryPassage(@"Page37", new string[]{  }, passage37_Main);
	}

	IStoryThread passage37_Main()
	{
		yield return text("\"Man!\" he snapped.  \"A man's cub.  Look!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page38", "Page38", null);
		yield break;
	}


	// .............
	// #38: Page38

	void passage38_Init()
	{
		this.Passages[@"Page38"] = new StoryPassage(@"Page38", new string[]{  }, passage38_Main);
	}

	IStoryThread passage38_Main()
	{
		yield return text("Directly in front of him, holding on by a low branch, stood a");
		yield return lineBreak();
		yield return text("naked brown baby who could just walk--as soft and as dimpled a");
		yield return lineBreak();
		yield return text("little atom as ever came to a wolf's cave at night.  He looked up");
		yield return lineBreak();
		yield return text("into Father Wolf's face, and laughed.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page39", "Page39", null);
		yield break;
	}


	// .............
	// #39: Page39

	void passage39_Init()
	{
		this.Passages[@"Page39"] = new StoryPassage(@"Page39", new string[]{  }, passage39_Main);
	}

	IStoryThread passage39_Main()
	{
		yield return text("\"Is that a man's cub?\" said Mother Wolf.  \"I have never seen");
		yield return lineBreak();
		yield return text("one.  Bring it here.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page40", "Page40", null);
		yield break;
	}


	// .............
	// #40: Page40

	void passage40_Init()
	{
		this.Passages[@"Page40"] = new StoryPassage(@"Page40", new string[]{  }, passage40_Main);
	}

	IStoryThread passage40_Main()
	{
		yield return text("A Wolf accustomed to moving his own cubs can, if necessary,");
		yield return lineBreak();
		yield return text("mouth an egg without breaking it, and though Father Wolf's jaws");
		yield return lineBreak();
		yield return text("closed right on the child's back not a tooth even scratched the");
		yield return lineBreak();
		yield return text("skin as he laid it down among the cubs.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page41", "Page41", null);
		yield break;
	}


	// .............
	// #41: Page41

	void passage41_Init()
	{
		this.Passages[@"Page41"] = new StoryPassage(@"Page41", new string[]{  }, passage41_Main);
	}

	IStoryThread passage41_Main()
	{
		yield return text("\"How little!  How naked, and--how bold!\" said Mother Wolf");
		yield return lineBreak();
		yield return text("softly.  The baby was pushing his way between the cubs to get");
		yield return lineBreak();
		yield return text("close to the warm hide. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page42", "Page42", null);
		yield break;
	}


	// .............
	// #42: Page42

	void passage42_Init()
	{
		this.Passages[@"Page42"] = new StoryPassage(@"Page42", new string[]{  }, passage42_Main);
	}

	IStoryThread passage42_Main()
	{
		yield return text("\"Ahai!  He is taking his meal with the");
		yield return lineBreak();
		yield return text("others.  And so this is a man's cub.  Now, was there ever a wolf");
		yield return lineBreak();
		yield return text("that could boast of a man's cub among her children?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page43", "Page43", null);
		yield break;
	}


	// .............
	// #43: Page43

	void passage43_Init()
	{
		this.Passages[@"Page43"] = new StoryPassage(@"Page43", new string[]{  }, passage43_Main);
	}

	IStoryThread passage43_Main()
	{
		yield return text("\"I have heard now and again of such a thing, but never in our");
		yield return lineBreak();
		yield return text("Pack or in my time,\" said Father Wolf. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page44", "Page44", null);
		yield break;
	}


	// .............
	// #44: Page44

	void passage44_Init()
	{
		this.Passages[@"Page44"] = new StoryPassage(@"Page44", new string[]{  }, passage44_Main);
	}

	IStoryThread passage44_Main()
	{
		yield return text("\"He is altogether without");
		yield return lineBreak();
		yield return text("hair, and I could kill him with a touch of my foot.  But see, he");
		yield return lineBreak();
		yield return text("looks up and is not afraid.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page45", "Page45", null);
		yield break;
	}


	// .............
	// #45: Page45

	void passage45_Init()
	{
		this.Passages[@"Page45"] = new StoryPassage(@"Page45", new string[]{  }, passage45_Main);
	}

	IStoryThread passage45_Main()
	{
		yield return text("The moonlight was blocked out of the mouth of the cave, for");
		yield return lineBreak();
		yield return text("Shere Khan's great square head and shoulders were thrust into the");
		yield return lineBreak();
		yield return text("entrance.  Tabaqui, behind him, was squeaking: \"My lord, my lord,");
		yield return lineBreak();
		yield return text("it went in here!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page46", "Page46", null);
		yield break;
	}


	// .............
	// #46: Page46

	void passage46_Init()
	{
		this.Passages[@"Page46"] = new StoryPassage(@"Page46", new string[]{  }, passage46_Main);
	}

	IStoryThread passage46_Main()
	{
		yield return text("\"Shere Khan does us great honor,\" said Father Wolf, but his");
		yield return lineBreak();
		yield return text("eyes were very angry.  \"What does Shere Khan need?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page47", "Page47", null);
		yield break;
	}


	// .............
	// #47: Page47

	void passage47_Init()
	{
		this.Passages[@"Page47"] = new StoryPassage(@"Page47", new string[]{  }, passage47_Main);
	}

	IStoryThread passage47_Main()
	{
		yield return text("\"My quarry.  A man's cub went this way,\" said Shere Khan.");
		yield return lineBreak();
		yield return text("\"Its parents have run off.  Give it to me.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page48", "Page48", null);
		yield break;
	}


	// .............
	// #48: Page48

	void passage48_Init()
	{
		this.Passages[@"Page48"] = new StoryPassage(@"Page48", new string[]{  }, passage48_Main);
	}

	IStoryThread passage48_Main()
	{
		yield return text("Shere Khan had jumped at a woodcutter's campfire, as Father");
		yield return lineBreak();
		yield return text("Wolf had said, and was furious from the pain of his burned feet.");
		yield return lineBreak();
		yield return text("But Father Wolf knew that the mouth of the cave was too narrow for");
		yield return lineBreak();
		yield return text("a tiger to come in by. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page49", "Page49", null);
		yield break;
	}


	// .............
	// #49: Page49

	void passage49_Init()
	{
		this.Passages[@"Page49"] = new StoryPassage(@"Page49", new string[]{  }, passage49_Main);
	}

	IStoryThread passage49_Main()
	{
		yield return text("Even where he was, Shere Khan's shoulders");
		yield return lineBreak();
		yield return text("and forepaws were cramped for want of room, as a man's would be if");
		yield return lineBreak();
		yield return text("he tried to fight in a barrel.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page50", "Page50", null);
		yield break;
	}


	// .............
	// #50: Page50

	void passage50_Init()
	{
		this.Passages[@"Page50"] = new StoryPassage(@"Page50", new string[]{  }, passage50_Main);
	}

	IStoryThread passage50_Main()
	{
		yield return text("\"The Wolves are a free people,\" said Father Wolf.  \"They take");
		yield return lineBreak();
		yield return text("orders from the Head of the Pack, and not from any striped");
		yield return lineBreak();
		yield return text("cattle-killer.  The man's cub is ours--to kill if we choose.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page51", "Page51", null);
		yield break;
	}


	// .............
	// #51: Page51

	void passage51_Init()
	{
		this.Passages[@"Page51"] = new StoryPassage(@"Page51", new string[]{  }, passage51_Main);
	}

	IStoryThread passage51_Main()
	{
		yield return text("\"Ye choose and ye do not choose!  What talk is this of");
		yield return lineBreak();
		yield return text("choosing?  By the bull that I killed, am I to stand nosing into");
		yield return lineBreak();
		yield return text("your dog's den for my fair dues?  It is I, Shere Khan, who speak!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page52", "Page52", null);
		yield break;
	}


	// .............
	// #52: Page52

	void passage52_Init()
	{
		this.Passages[@"Page52"] = new StoryPassage(@"Page52", new string[]{  }, passage52_Main);
	}

	IStoryThread passage52_Main()
	{
		yield return text("The tiger's roar filled the cave with thunder.  Mother Wolf");
		yield return lineBreak();
		yield return text("shook herself clear of the cubs and sprang forward, her eyes, like");
		yield return lineBreak();
		yield return text("two green moons in the darkness, facing the blazing eyes of Shere");
		yield return lineBreak();
		yield return text("Khan.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page53", "Page53", null);
		yield break;
	}


	// .............
	// #53: Page53

	void passage53_Init()
	{
		this.Passages[@"Page53"] = new StoryPassage(@"Page53", new string[]{  }, passage53_Main);
	}

	IStoryThread passage53_Main()
	{
		yield return text("\"And it is I, Raksha ");
		using (Group("hook", "")) {
			yield return text("The Demon");
		}
		yield return text(", who answers.  The man's cub");
		yield return lineBreak();
		yield return text("is mine, Lungri--mine to me!  He shall not be killed.  He shall");
		yield return lineBreak();
		yield return text("live to run with the Pack and to hunt with the Pack; and in the");
		yield return lineBreak();
		yield return text("end, look you, hunter of little naked cubs--frog-eater--");
		yield return lineBreak();
		yield return text("fish-killer--he shall hunt thee!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page54", "Page54", null);
		yield break;
	}


	// .............
	// #54: Page54

	void passage54_Init()
	{
		this.Passages[@"Page54"] = new StoryPassage(@"Page54", new string[]{  }, passage54_Main);
	}

	IStoryThread passage54_Main()
	{
		yield return text("Now get hence, or by the");
		yield return lineBreak();
		yield return text("Sambhur that I killed (I eat no starved cattle), back thou goest");
		yield return lineBreak();
		yield return text("to thy mother, burned beast of the jungle, lamer than ever thou");
		yield return lineBreak();
		yield return text("camest into the world!  Go!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page55", "Page55", null);
		yield break;
	}


	// .............
	// #55: Page55

	void passage55_Init()
	{
		this.Passages[@"Page55"] = new StoryPassage(@"Page55", new string[]{  }, passage55_Main);
	}

	IStoryThread passage55_Main()
	{
		yield return text("Father Wolf looked on amazed.  He had almost forgotten the");
		yield return lineBreak();
		yield return text("days when he won Mother Wolf in fair fight from five other wolves,");
		yield return lineBreak();
		yield return text("when she ran in the Pack and was not called The Demon for");
		yield return lineBreak();
		yield return text("compliment's sake.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page56", "Page56", null);
		yield break;
	}


	// .............
	// #56: Page56

	void passage56_Init()
	{
		this.Passages[@"Page56"] = new StoryPassage(@"Page56", new string[]{  }, passage56_Main);
	}

	IStoryThread passage56_Main()
	{
		yield return text("Shere Khan might have faced Father Wolf, but");
		yield return lineBreak();
		yield return text("he could not stand up against Mother Wolf, for he knew that where");
		yield return lineBreak();
		yield return text("he was she had all the advantage of the ground, and would fight to");
		yield return lineBreak();
		yield return text("the death.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page57", "Page57", null);
		yield break;
	}


	// .............
	// #57: Page57

	void passage57_Init()
	{
		this.Passages[@"Page57"] = new StoryPassage(@"Page57", new string[]{  }, passage57_Main);
	}

	IStoryThread passage57_Main()
	{
		yield return text("So he backed out of the cave mouth growling, and when");
		yield return lineBreak();
		yield return text("he was clear he shouted:");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page58", "Page58", null);
		yield break;
	}


	// .............
	// #58: Page58

	void passage58_Init()
	{
		this.Passages[@"Page58"] = new StoryPassage(@"Page58", new string[]{  }, passage58_Main);
	}

	IStoryThread passage58_Main()
	{
		yield return text("\"Each dog barks in his own yard!  We will see what the Pack");
		yield return lineBreak();
		yield return text("will say to this fostering of man-cubs.  The cub is mine, and to");
		yield return lineBreak();
		yield return text("my teeth he will come in the end, O bush-tailed thieves!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page59", "Page59", null);
		yield break;
	}


	// .............
	// #59: Page59

	void passage59_Init()
	{
		this.Passages[@"Page59"] = new StoryPassage(@"Page59", new string[]{  }, passage59_Main);
	}

	IStoryThread passage59_Main()
	{
		yield return text("Mother Wolf threw herself down panting among the cubs, and");
		yield return lineBreak();
		yield return text("Father Wolf said to her gravely:");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page60", "Page60", null);
		yield break;
	}


	// .............
	// #60: Page60

	void passage60_Init()
	{
		this.Passages[@"Page60"] = new StoryPassage(@"Page60", new string[]{  }, passage60_Main);
	}

	IStoryThread passage60_Main()
	{
		yield return text("\"Shere Khan speaks this much truth.  The cub must be shown to");
		yield return lineBreak();
		yield return text("the Pack.  Wilt thou still keep him, Mother?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page61", "Page61", null);
		yield break;
	}


	// .............
	// #61: Page61

	void passage61_Init()
	{
		this.Passages[@"Page61"] = new StoryPassage(@"Page61", new string[]{  }, passage61_Main);
	}

	IStoryThread passage61_Main()
	{
		yield return text("\"Keep him!\" she gasped.  \"He came naked, by night, alone and");
		yield return lineBreak();
		yield return text("very hungry; yet he was not afraid!  Look, he has pushed one of my");
		yield return lineBreak();
		yield return text("babes to one side already.  And that lame butcher would have");
		yield return lineBreak();
		yield return text("killed him and would have run off to the Waingunga while the");
		yield return lineBreak();
		yield return text("villagers here hunted through all our lairs in revenge!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page62", "Page62", null);
		yield break;
	}


	// .............
	// #62: Page62

	void passage62_Init()
	{
		this.Passages[@"Page62"] = new StoryPassage(@"Page62", new string[]{  }, passage62_Main);
	}

	IStoryThread passage62_Main()
	{
		yield return text("Keep him?");
		yield return lineBreak();
		yield return text("Assuredly I will keep him.  Lie still, little frog.  O thou Mowgli");
		yield return lineBreak();
		yield return text("--for Mowgli the Frog I will call thee--the time will come when");
		yield return lineBreak();
		yield return text("thou wilt hunt Shere Khan as he has hunted thee.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page63", "Page63", null);
		yield break;
	}


	// .............
	// #63: Page63

	void passage63_Init()
	{
		this.Passages[@"Page63"] = new StoryPassage(@"Page63", new string[]{  }, passage63_Main);
	}

	IStoryThread passage63_Main()
	{
		yield return text("\"But what will our Pack say?\" said Father Wolf.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page64", "Page64", null);
		yield break;
	}


	// .............
	// #64: Page64

	void passage64_Init()
	{
		this.Passages[@"Page64"] = new StoryPassage(@"Page64", new string[]{  }, passage64_Main);
	}

	IStoryThread passage64_Main()
	{
		yield return text("The Law of the Jungle lays down very clearly that any wolf");
		yield return lineBreak();
		yield return text("may, when he marries, withdraw from the Pack he belongs to.  But");
		yield return lineBreak();
		yield return text("as soon as his cubs are old enough to stand on their feet he must");
		yield return lineBreak();
		yield return text("bring them to the Pack Council, which is generally held once a");
		yield return lineBreak();
		yield return text("month at full moon, in order that the other wolves may identify");
		yield return lineBreak();
		yield return text("them.  ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page65", "Page65", null);
		yield break;
	}


	// .............
	// #65: Page65

	void passage65_Init()
	{
		this.Passages[@"Page65"] = new StoryPassage(@"Page65", new string[]{  }, passage65_Main);
	}

	IStoryThread passage65_Main()
	{
		yield return text("After that inspection the cubs are free to run where they");
		yield return lineBreak();
		yield return text("please, and until they have killed their first buck no excuse is");
		yield return lineBreak();
		yield return text("accepted if a grown wolf of the Pack kills one of them.  The");
		yield return lineBreak();
		yield return text("punishment is death where the murderer can be found; and if you");
		yield return lineBreak();
		yield return text("think for a minute you will see that this must be so.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page66", "Page66", null);
		yield break;
	}


	// .............
	// #66: Page66

	void passage66_Init()
	{
		this.Passages[@"Page66"] = new StoryPassage(@"Page66", new string[]{  }, passage66_Main);
	}

	IStoryThread passage66_Main()
	{
		yield return text("Father Wolf waited till his cubs could run a little, and then");
		yield return lineBreak();
		yield return text("on the night of the Pack Meeting took them and Mowgli and Mother");
		yield return lineBreak();
		yield return text("Wolf to the Council Rock--a hilltop covered with stones and");
		yield return lineBreak();
		yield return text("boulders where a hundred wolves could hide.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page67", "Page67", null);
		yield break;
	}


	// .............
	// #67: Page67

	void passage67_Init()
	{
		this.Passages[@"Page67"] = new StoryPassage(@"Page67", new string[]{  }, passage67_Main);
	}

	IStoryThread passage67_Main()
	{
		yield return text("Akela, the great gray");
		yield return lineBreak();
		yield return text("Lone Wolf, who led all the Pack by strength and cunning, lay out");
		yield return lineBreak();
		yield return text("at full length on his rock, and below him sat forty or more wolves");
		yield return lineBreak();
		yield return text("of every size and color, from badger-colored veterans who could");
		yield return lineBreak();
		yield return text("handle a buck alone to young black three-year-olds who thought");
		yield return lineBreak();
		yield return text("they could.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page68", "Page68", null);
		yield break;
	}


	// .............
	// #68: Page68

	void passage68_Init()
	{
		this.Passages[@"Page68"] = new StoryPassage(@"Page68", new string[]{  }, passage68_Main);
	}

	IStoryThread passage68_Main()
	{
		yield return text("The Lone Wolf had led them for a year now.  He had");
		yield return lineBreak();
		yield return text("fallen twice into a wolf trap in his youth, and once he had been");
		yield return lineBreak();
		yield return text("beaten and left for dead; so he knew the manners and customs of");
		yield return lineBreak();
		yield return text("men.  There was very little talking at the Rock.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page69", "Page69", null);
		yield break;
	}


	// .............
	// #69: Page69

	void passage69_Init()
	{
		this.Passages[@"Page69"] = new StoryPassage(@"Page69", new string[]{  }, passage69_Main);
	}

	IStoryThread passage69_Main()
	{
		yield return text("The cubs tumbled");
		yield return lineBreak();
		yield return text("over each other in the center of the circle where their mothers");
		yield return lineBreak();
		yield return text("and fathers sat, and now and again a senior wolf would go quietly");
		yield return lineBreak();
		yield return text("up to a cub, look at him carefully, and return to his place on");
		yield return lineBreak();
		yield return text("noiseless feet.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page70", "Page70", null);
		yield break;
	}


	// .............
	// #70: Page70

	void passage70_Init()
	{
		this.Passages[@"Page70"] = new StoryPassage(@"Page70", new string[]{  }, passage70_Main);
	}

	IStoryThread passage70_Main()
	{
		yield return text("Sometimes a mother would push her cub far out");
		yield return lineBreak();
		yield return text("into the moonlight to be sure that he had not been overlooked.");
		yield return lineBreak();
		yield return text("Akela from his rock would cry: \"Ye know the Law--ye know the");
		yield return lineBreak();
		yield return text("Law.  Look well, O Wolves!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page71", "Page71", null);
		yield break;
	}


	// .............
	// #71: Page71

	void passage71_Init()
	{
		this.Passages[@"Page71"] = new StoryPassage(@"Page71", new string[]{  }, passage71_Main);
	}

	IStoryThread passage71_Main()
	{
		yield return text("And the anxious mothers would take up");
		yield return lineBreak();
		yield return text("the call: \"Look--look well, O Wolves!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page72", "Page72", null);
		yield break;
	}


	// .............
	// #72: Page72

	void passage72_Init()
	{
		this.Passages[@"Page72"] = new StoryPassage(@"Page72", new string[]{  }, passage72_Main);
	}

	IStoryThread passage72_Main()
	{
		yield return text("At last--and Mother Wolf's neck bristles lifted as the time");
		yield return lineBreak();
		yield return text("came--Father Wolf pushed \"Mowgli the Frog,\" as they called him,");
		yield return lineBreak();
		yield return text("into the center, where he sat laughing and playing with some");
		yield return lineBreak();
		yield return text("pebbles that glistened in the moonlight.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page73", "Page73", null);
		yield break;
	}


	// .............
	// #73: Page73

	void passage73_Init()
	{
		this.Passages[@"Page73"] = new StoryPassage(@"Page73", new string[]{  }, passage73_Main);
	}

	IStoryThread passage73_Main()
	{
		yield return text("Akela never raised his head from his paws, but went on with");
		yield return lineBreak();
		yield return text("the monotonous cry: \"Look well!\"  A muffled roar came up from");
		yield return lineBreak();
		yield return text("behind the rocks--the voice of Shere Khan crying: \"The cub is");
		yield return lineBreak();
		yield return text("mine.  Give him to me.  What have the Free People to do with a");
		yield return lineBreak();
		yield return text("man's cub?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page74", "Page74", null);
		yield break;
	}


	// .............
	// #74: Page74

	void passage74_Init()
	{
		this.Passages[@"Page74"] = new StoryPassage(@"Page74", new string[]{  }, passage74_Main);
	}

	IStoryThread passage74_Main()
	{
		yield return text("Akela never even twitched his ears.  All he said was:");
		yield return lineBreak();
		yield return text("\"Look well, O Wolves!  What have the Free People to do with the");
		yield return lineBreak();
		yield return text("orders of any save the Free People?  Look well!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page75", "Page75", null);
		yield break;
	}


	// .............
	// #75: Page75

	void passage75_Init()
	{
		this.Passages[@"Page75"] = new StoryPassage(@"Page75", new string[]{  }, passage75_Main);
	}

	IStoryThread passage75_Main()
	{
		yield return text("There was a chorus of deep growls, and a young wolf in his");
		yield return lineBreak();
		yield return text("fourth year flung back Shere Khan's question to Akela: \"What have");
		yield return lineBreak();
		yield return text("the Free People to do with a man's cub?\" ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page76", "Page76", null);
		yield break;
	}


	// .............
	// #76: Page76

	void passage76_Init()
	{
		this.Passages[@"Page76"] = new StoryPassage(@"Page76", new string[]{  }, passage76_Main);
	}

	IStoryThread passage76_Main()
	{
		yield return text("Now, the Law of the");
		yield return lineBreak();
		yield return text("Jungle lays down that if there is any dispute as to the right of a");
		yield return lineBreak();
		yield return text("cub to be accepted by the Pack, he must be spoken for by at least");
		yield return lineBreak();
		yield return text("two members of the Pack who are not his father and mother.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page77", "Page77", null);
		yield break;
	}


	// .............
	// #77: Page77

	void passage77_Init()
	{
		this.Passages[@"Page77"] = new StoryPassage(@"Page77", new string[]{  }, passage77_Main);
	}

	IStoryThread passage77_Main()
	{
		yield return text("\"Who speaks for this cub?\" said Akela.  \"Among the Free People");
		yield return lineBreak();
		yield return text("who speaks?\"  There was no answer and Mother Wolf got ready for");
		yield return lineBreak();
		yield return text("what she knew would be her last fight, if things came to fighting.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page78", "Page78", null);
		yield break;
	}


	// .............
	// #78: Page78

	void passage78_Init()
	{
		this.Passages[@"Page78"] = new StoryPassage(@"Page78", new string[]{  }, passage78_Main);
	}

	IStoryThread passage78_Main()
	{
		yield return text("Then the only other creature who is allowed at the Pack");
		yield return lineBreak();
		yield return text("Council--Baloo, the sleepy brown bear who teaches the wolf cubs");
		yield return lineBreak();
		yield return text("the Law of the Jungle: old Baloo, who can come and go where he");
		yield return lineBreak();
		yield return text("pleases because he eats only nuts and roots and honey--rose upon");
		yield return lineBreak();
		yield return text("his hind quarters and grunted.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page79", "Page79", null);
		yield break;
	}


	// .............
	// #79: Page79

	void passage79_Init()
	{
		this.Passages[@"Page79"] = new StoryPassage(@"Page79", new string[]{  }, passage79_Main);
	}

	IStoryThread passage79_Main()
	{
		yield return text("\"The man's cub--the man's cub?\" he said.  \"I speak for the");
		yield return lineBreak();
		yield return text("man's cub.  There is no harm in a man's cub.  I have no gift of");
		yield return lineBreak();
		yield return text("words, but I speak the truth.  Let him run with the Pack, and be");
		yield return lineBreak();
		yield return text("entered with the others.  I myself will teach him.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page80", "Page80", null);
		yield break;
	}


	// .............
	// #80: Page80

	void passage80_Init()
	{
		this.Passages[@"Page80"] = new StoryPassage(@"Page80", new string[]{  }, passage80_Main);
	}

	IStoryThread passage80_Main()
	{
		yield return text("\"We need yet another,\" said Akela.  \"Baloo has spoken, and he");
		yield return lineBreak();
		yield return text("is our teacher for the young cubs.  Who speaks besides Baloo?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page81", "Page81", null);
		yield break;
	}


	// .............
	// #81: Page81

	void passage81_Init()
	{
		this.Passages[@"Page81"] = new StoryPassage(@"Page81", new string[]{  }, passage81_Main);
	}

	IStoryThread passage81_Main()
	{
		yield return text("A black shadow dropped down into the circle.  It was Bagheera");
		yield return lineBreak();
		yield return text("the Black Panther, inky black all over, but with the panther");
		yield return lineBreak();
		yield return text("markings showing up in certain lights like the pattern of watered");
		yield return lineBreak();
		yield return text("silk.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page82", "Page82", null);
		yield break;
	}


	// .............
	// #82: Page82

	void passage82_Init()
	{
		this.Passages[@"Page82"] = new StoryPassage(@"Page82", new string[]{  }, passage82_Main);
	}

	IStoryThread passage82_Main()
	{
		yield return text("Everybody knew Bagheera, and nobody cared to cross his");
		yield return lineBreak();
		yield return text("path; for he was as cunning as Tabaqui, as bold as the wild");
		yield return lineBreak();
		yield return text("buffalo, and as reckless as the wounded elephant.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page83", "Page83", null);
		yield break;
	}


	// .............
	// #83: Page83

	void passage83_Init()
	{
		this.Passages[@"Page83"] = new StoryPassage(@"Page83", new string[]{  }, passage83_Main);
	}

	IStoryThread passage83_Main()
	{
		yield return text("But he had a");
		yield return lineBreak();
		yield return text("voice as soft as wild honey dripping from a tree, and a skin");
		yield return lineBreak();
		yield return text("softer than down.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page84", "Page84", null);
		yield break;
	}


	// .............
	// #84: Page84

	void passage84_Init()
	{
		this.Passages[@"Page84"] = new StoryPassage(@"Page84", new string[]{  }, passage84_Main);
	}

	IStoryThread passage84_Main()
	{
		yield return text("\"O Akela, and ye the Free People,\" he purred, \"I have no right");
		yield return lineBreak();
		yield return text("in your assembly, but the Law of the Jungle says that if there is");
		yield return lineBreak();
		yield return text("a doubt which is not a killing matter in regard to a new cub, the");
		yield return lineBreak();
		yield return text("life of that cub may be bought at a price.  And the Law does not");
		yield return lineBreak();
		yield return text("say who may or may not pay that price.  Am I right?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page85", "Page85", null);
		yield break;
	}


	// .............
	// #85: Page85

	void passage85_Init()
	{
		this.Passages[@"Page85"] = new StoryPassage(@"Page85", new string[]{  }, passage85_Main);
	}

	IStoryThread passage85_Main()
	{
		yield return text("\"Good!  Good!\" said the young wolves, who are always hungry.");
		yield return lineBreak();
		yield return text("\"Listen to Bagheera.  The cub can be bought for a price.  It is");
		yield return lineBreak();
		yield return text("the Law.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page86", "Page86", null);
		yield break;
	}


	// .............
	// #86: Page86

	void passage86_Init()
	{
		this.Passages[@"Page86"] = new StoryPassage(@"Page86", new string[]{  }, passage86_Main);
	}

	IStoryThread passage86_Main()
	{
		yield return text("\"Knowing that I have no right to speak here, I ask your");
		yield return lineBreak();
		yield return text("leave.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page87", "Page87", null);
		yield break;
	}


	// .............
	// #87: Page87

	void passage87_Init()
	{
		this.Passages[@"Page87"] = new StoryPassage(@"Page87", new string[]{  }, passage87_Main);
	}

	IStoryThread passage87_Main()
	{
		yield return text("\"Speak then,\" cried twenty voices.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page88", "Page88", null);
		yield break;
	}


	// .............
	// #88: Page88

	void passage88_Init()
	{
		this.Passages[@"Page88"] = new StoryPassage(@"Page88", new string[]{  }, passage88_Main);
	}

	IStoryThread passage88_Main()
	{
		yield return text("\"To kill a naked cub is shame.  Besides, he may make better");
		yield return lineBreak();
		yield return text("sport for you when he is grown.  Baloo has spoken in his behalf.");
		yield return lineBreak();
		yield return text("Now to Baloo's word I will add one bull, and a fat one, newly");
		yield return lineBreak();
		yield return text("killed, not half a mile from here, if ye will accept the man's cub");
		yield return lineBreak();
		yield return text("according to the Law.  Is it difficult?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page89", "Page89", null);
		yield break;
	}


	// .............
	// #89: Page89

	void passage89_Init()
	{
		this.Passages[@"Page89"] = new StoryPassage(@"Page89", new string[]{  }, passage89_Main);
	}

	IStoryThread passage89_Main()
	{
		yield return text("There was a clamor of scores of voices, saying: \"What matter?");
		yield return lineBreak();
		yield return text("He will die in the winter rains.  He will scorch in the sun.  What");
		yield return lineBreak();
		yield return text("harm can a naked frog do us?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page90", "Page90", null);
		yield break;
	}


	// .............
	// #90: Page90

	void passage90_Init()
	{
		this.Passages[@"Page90"] = new StoryPassage(@"Page90", new string[]{  }, passage90_Main);
	}

	IStoryThread passage90_Main()
	{
		yield return text("Let him run with the Pack.  Where is");
		yield return lineBreak();
		yield return text("the bull, Bagheera?  Let him be accepted.\"  And then came Akela's");
		yield return lineBreak();
		yield return text("deep bay, crying: \"Look well--look well, O Wolves!\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page91", "Page91", null);
		yield break;
	}


	// .............
	// #91: Page91

	void passage91_Init()
	{
		this.Passages[@"Page91"] = new StoryPassage(@"Page91", new string[]{  }, passage91_Main);
	}

	IStoryThread passage91_Main()
	{
		yield return text("Mowgli was still deeply interested in the pebbles, and he did");
		yield return lineBreak();
		yield return text("not notice when the wolves came and looked at him one by one.  At");
		yield return lineBreak();
		yield return text("last they all went down the hill for the dead bull, and only");
		yield return lineBreak();
		yield return text("Akela, Bagheera, Baloo, and Mowgli's own wolves were left.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page92", "Page92", null);
		yield break;
	}


	// .............
	// #92: Page92

	void passage92_Init()
	{
		this.Passages[@"Page92"] = new StoryPassage(@"Page92", new string[]{  }, passage92_Main);
	}

	IStoryThread passage92_Main()
	{
		yield return text("Shere Khan roared still in the night, for he was very angry that Mowgli");
		yield return lineBreak();
		yield return text("had not been handed over to him.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page93", "Page93", null);
		yield break;
	}


	// .............
	// #93: Page93

	void passage93_Init()
	{
		this.Passages[@"Page93"] = new StoryPassage(@"Page93", new string[]{  }, passage93_Main);
	}

	IStoryThread passage93_Main()
	{
		yield return text("\"Ay, roar well,\" said Bagheera, under his whiskers, \"for the");
		yield return lineBreak();
		yield return text("time will come when this naked thing will make thee roar to");
		yield return lineBreak();
		yield return text("another tune, or I know nothing of man.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page94", "Page94", null);
		yield break;
	}


	// .............
	// #94: Page94

	void passage94_Init()
	{
		this.Passages[@"Page94"] = new StoryPassage(@"Page94", new string[]{  }, passage94_Main);
	}

	IStoryThread passage94_Main()
	{
		yield return text("\"It was well done,\" said Akela.  \"Men and their cubs are very");
		yield return lineBreak();
		yield return text("wise.  He may be a help in time.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page95", "Page95", null);
		yield break;
	}


	// .............
	// #95: Page95

	void passage95_Init()
	{
		this.Passages[@"Page95"] = new StoryPassage(@"Page95", new string[]{  }, passage95_Main);
	}

	IStoryThread passage95_Main()
	{
		yield return text("\"Truly, a help in time of need; for none can hope to lead the");
		yield return lineBreak();
		yield return text("Pack forever,\" said Bagheera.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page96", "Page96", null);
		yield break;
	}


	// .............
	// #96: Page96

	void passage96_Init()
	{
		this.Passages[@"Page96"] = new StoryPassage(@"Page96", new string[]{  }, passage96_Main);
	}

	IStoryThread passage96_Main()
	{
		yield return text("Akela said nothing.  He was thinking of the time that comes to");
		yield return lineBreak();
		yield return text("every leader of every pack when his strength goes from him and he");
		yield return lineBreak();
		yield return text("gets feebler and feebler, till at last he is killed by the wolves");
		yield return lineBreak();
		yield return text("and a new leader comes up--to be killed in his turn.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page97", "Page97", null);
		yield break;
	}


	// .............
	// #97: Page97

	void passage97_Init()
	{
		this.Passages[@"Page97"] = new StoryPassage(@"Page97", new string[]{  }, passage97_Main);
	}

	IStoryThread passage97_Main()
	{
		yield return text("\"Take him away,\" he said to Father Wolf, \"and train him as");
		yield return lineBreak();
		yield return text("befits one of the Free People.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page98", "Page98", null);
		yield break;
	}


	// .............
	// #98: Page98

	void passage98_Init()
	{
		this.Passages[@"Page98"] = new StoryPassage(@"Page98", new string[]{  }, passage98_Main);
	}

	IStoryThread passage98_Main()
	{
		yield return text("And that is how Mowgli was entered into the Seeonee Wolf Pack");
		yield return lineBreak();
		yield return text("for the price of a bull and on Baloo's good word.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page99", "Page99", null);
		yield break;
	}


	// .............
	// #99: Page99

	void passage99_Init()
	{
		this.Passages[@"Page99"] = new StoryPassage(@"Page99", new string[]{  }, passage99_Main);
	}

	IStoryThread passage99_Main()
	{
		yield return text("ACHIEVEMENT");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("100 PAGES");
		yield return lineBreak();
		yield break;
	}


}