/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Sample1.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Sample1: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Sample1()
	{
		this.StartPassage = "Chapter 1: Mowgli's Brothers";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Chapter 1: Mowgli's Brothers

	void passage1_Init()
	{
		this.Passages[@"Chapter 1: Mowgli's Brothers"] = new StoryPassage(@"Chapter 1: Mowgli's Brothers", new string[]{ "Page1", }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("   Now Rann the Kite brings home the night");
		yield return lineBreak();
		yield return text("      That Mang the Bat sets free--");
		yield return lineBreak();
		yield return text("   The herds are shut in byre and hut");
		yield return lineBreak();
		yield return text("      For loosed till dawn are we.");
		yield return lineBreak();
		yield return text("   This is the hour of pride and power,");
		yield return lineBreak();
		yield return text("      Talon and tush and claw.");
		yield return lineBreak();
		yield return text("   Oh, hear the call!--Good hunting all");
		yield return lineBreak();
		yield return text("      That keep the Jungle Law!");
		yield return lineBreak();
		yield return text("   Night-Song in the Jungle");
		yield return lineBreak();
		yield return text("   ");
		yield return lineBreak();
		yield return link("Page2", "Page2", null);
		yield break;
	}


	// .............
	// #2: Page2

	void passage2_Init()
	{
		this.Passages[@"Page2"] = new StoryPassage(@"Page2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("It was seven o'clock of a very warm evening in the Seeonee hills");
		yield return lineBreak();
		yield return text("when Father Wolf woke up from his day's rest, scratched himself,");
		yield return lineBreak();
		yield return text("yawned, and spread out his paws one after the other to get rid of");
		yield return lineBreak();
		yield return text("the sleepy feeling in their tips.  Mother Wolf lay with her big");
		yield return lineBreak();
		yield return text("gray nose dropped across her four tumbling, squealing cubs, and");
		yield return lineBreak();
		yield return text("the moon shone into the mouth of the cave where they all lived.");
		yield return lineBreak();
		yield return text("\"Augrh!\" said Father Wolf.  \"It is time to hunt again.\"  He was");
		yield return lineBreak();
		yield return text("going to spring down hill when a little shadow with a bushy tail");
		yield return lineBreak();
		yield return text("crossed the threshold and whined: \"Good luck go with you, O Chief");
		yield return lineBreak();
		yield return text("of the Wolves.  And good luck and strong white teeth go with noble");
		yield return lineBreak();
		yield return text("children that they may never forget the hungry in this world.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page3", "Page3", null);
		yield break;
	}


	// .............
	// #3: Page3

	void passage3_Init()
	{
		this.Passages[@"Page3"] = new StoryPassage(@"Page3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("It was the jackal--Tabaqui, the Dish-licker--and the");
		yield return lineBreak();
		yield return text("wolves of India despise Tabaqui because he runs about making");
		yield return lineBreak();
		yield return text("mischief, and telling tales, and eating rags and pieces of leather");
		yield return lineBreak();
		yield return text("from the village rubbish-heaps.  But they are afraid of him too,");
		yield return lineBreak();
		yield return text("because Tabaqui, more than anyone else in the jungle, is apt to go");
		yield return lineBreak();
		yield return text("mad, and then he forgets that he was ever afraid of anyone, and");
		yield return lineBreak();
		yield return text("runs through the forest biting everything in his way.  Even the");
		yield return lineBreak();
		yield return text("tiger runs and hides when little Tabaqui goes mad, for madness is");
		yield return lineBreak();
		yield return text("the most disgraceful thing that can overtake a wild creature.  We");
		yield return lineBreak();
		yield return text("call it hydrophobia, but they call it dewanee--the madness--");
		yield return lineBreak();
		yield return text("and run.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page4", "Page4", null);
		yield break;
	}


	// .............
	// #4: Page4

	void passage4_Init()
	{
		this.Passages[@"Page4"] = new StoryPassage(@"Page4", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("\"Enter, then, and look,\" said Father Wolf stiffly, \"but there");
		yield return lineBreak();
		yield return text("is no food here.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("\"For a wolf, no,\" said Tabaqui, \"but for so mean a person as");
		yield return lineBreak();
		yield return text("myself a dry bone is a good feast.  Who are we, the Gidur-log ");
		using (Group("hook", "")) {
			yield return text("the");
			yield return lineBreak();
			yield return text("jackal people");
		}
		yield return text(", to pick and choose?\"  He scuttled to the back of");
		yield return lineBreak();
		yield return text("the cave, where he found the bone of a buck with some meat on it,");
		yield return lineBreak();
		yield return text("and sat cracking the end merrily.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page5", "Page5", null);
		yield break;
	}


	// .............
	// #5: Page5

	void passage5_Init()
	{
		this.Passages[@"Page5"] = new StoryPassage(@"Page5", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("\"All thanks for this good meal,\" he said, licking his lips.");
		yield return lineBreak();
		yield return text("\"How beautiful are the noble children!  How large are their eyes!");
		yield return lineBreak();
		yield return text("And so young too!  Indeed, indeed, I might have remembered that");
		yield return lineBreak();
		yield return text("the children of kings are men from the beginning.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Now, Tabaqui knew as well as anyone else that there is nothing");
		yield return lineBreak();
		yield return text("so unlucky as to compliment children to their faces.  It pleased");
		yield return lineBreak();
		yield return text("him to see Mother and Father Wolf look uncomfortable.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Page6", "Page6", null);
		yield break;
	}


	// .............
	// #6: Page6

	void passage6_Init()
	{
		this.Passages[@"Page6"] = new StoryPassage(@"Page6", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}